version: '3.8'

services:
  web:
    build:
       context: ./django_api
       dockerfile: Dockerfile.prod
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    # Открываем порт 8000 наружу
    expose:
      - 8000
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/django_api/web/static
      - media_volume:/home/django_api/web/media
    env_file:
      - ./.env.prod
    # Дожидаемся запуска db
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/django_api/web/static
      - media_volume:/home/django_api/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_volume:
  static_volume:
  media_volume: