version: '3.3'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: .
    restart: always
    expose:
      - 8000
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
      - ./dump.json:/code/dump.json
    depends_on:
      - db
    env_file:
      - .env

      nginx:
        image: nginx:1.19.2
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
          - ./configs:/etc/nginx/conf.d:ro
        depends_on:
          - web
        ports:
          - "80:80" 


volumes:
  postgres_data: 
  static_value:
  media_value: